class: APEffect

params:
  qpar:
    prior:
      dist: uniform
      limits: [0.8, 1.2]
    latex: '\alpha_{\parallel}'
  qper:
    prior:
      dist: uniform
      limits: [0.8, 1.2]
    latex: '\alpha_{\perp}'
  qiso:
    prior:
      dist: uniform
      limits: [0.8, 1.2]
    latex: '\alpha_{\mathrm{iso}}'
  qap:
    prior:
      dist: uniform
      limits: [0.8, 1.2]
    latex: '\alpha_{\mathrm{ap}}'
  betaphi:
    prior:
      dist: uniform
      limits: [-8.0, 10.0]
    latex: '\beta_{\phi}'
